"""add message_targets association table and messages table

Revision ID: b4a78bfcc04f
Revises: fbbf3b539a23
Create Date: 2025-06-05 16:04:59.180879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4a78bfcc04f'
down_revision: Union[str, None] = 'fbbf3b539a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_targets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('message_targets_message_id_fkey'), 'message_targets', type_='foreignkey')
    op.drop_constraint(op.f('message_targets_course_id_fkey'), 'message_targets', type_='foreignkey')
    op.drop_constraint(op.f('message_targets_institution_id_fkey'), 'message_targets', type_='foreignkey')
    op.drop_constraint(op.f('message_targets_class_group_id_fkey'), 'message_targets', type_='foreignkey')
    op.create_foreign_key(None, 'message_targets', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(None, 'message_targets', 'users', ['user_id'], ['id'])
    op.drop_column('message_targets', 'updated_at')
    op.drop_column('message_targets', 'course_id')
    op.drop_column('message_targets', 'institution_id')
    op.drop_column('message_targets', 'class_group_id')
    op.drop_column('message_targets', 'deleted_at')
    op.drop_column('message_targets', 'created_at')
    op.drop_column('message_targets', 'id')
    op.add_column('messages', sa.Column('titulo', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('mensagem', sa.Text(), nullable=True))
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'expires_at')
    op.drop_column('messages', 'send_at')
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('send_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_column('messages', 'mensagem')
    op.drop_column('messages', 'titulo')
    op.add_column('message_targets', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('message_targets', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('message_targets', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('message_targets', sa.Column('class_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message_targets', sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message_targets', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message_targets', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message_targets', type_='foreignkey')
    op.drop_constraint(None, 'message_targets', type_='foreignkey')
    op.create_foreign_key(op.f('message_targets_class_group_id_fkey'), 'message_targets', 'class_groups', ['class_group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('message_targets_institution_id_fkey'), 'message_targets', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('message_targets_course_id_fkey'), 'message_targets', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('message_targets_message_id_fkey'), 'message_targets', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_column('message_targets', 'user_id')
    # ### end Alembic commands ###
