"""Atualizar ClassSessions e ClassGroup - remover campos, adicionar novos campos e teacher_id

Revision ID: fbbf3b539a23
Revises: 
Create Date: 2025-05-26 02:00:17.069588

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'fbbf3b539a23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Adicionar teacher_id à tabela class_groups
    op.add_column('class_groups', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'class_groups', 'users', ['teacher_id'], ['id'])
    
    # Adicionar a coluna date como nullable primeiro
    op.add_column('class_sessions', sa.Column('date', sa.Date(), nullable=True))
    
    # Atualizar registros existentes com uma data baseada no created_at
    # Ajuste esta lógica conforme necessário para sua regra de negócio
    op.execute(text("""
        UPDATE class_sessions 
        SET date = created_at::date 
        WHERE date IS NULL
    """))
    
    # Agora tornar a coluna NOT NULL
    op.alter_column('class_sessions', 'date', nullable=False)
    
    # Adicionar outras colunas
    op.add_column('class_sessions', sa.Column('confirmed_at', sa.Boolean(), nullable=True, default=False))
    op.add_column('class_sessions', sa.Column('canceled', sa.Boolean(), nullable=True, default=False))
    op.add_column('class_sessions', sa.Column('canceled_desc', sa.String(length=500), nullable=True))
    
    # Remover constraints antigas
    op.drop_constraint(op.f('class_sessions_subject_id_fkey'), 'class_sessions', type_='foreignkey')
    op.drop_constraint(op.f('class_sessions_period_id_fkey'), 'class_sessions', type_='foreignkey')
    
    # Remover colunas antigas
    op.drop_column('class_sessions', 'subject_id')
    op.drop_column('class_sessions', 'period_id')
    op.drop_column('class_sessions', 'teacher_id')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Readicionar colunas removidas
    op.add_column('class_sessions', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('class_sessions', sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('class_sessions', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Recriar foreign keys
    op.create_foreign_key(op.f('class_sessions_period_id_fkey'), 'class_sessions', 'periods', ['period_id'], ['id'])
    op.create_foreign_key(op.f('class_sessions_subject_id_fkey'), 'class_sessions', 'subjects', ['subject_id'], ['id'])
    
    # Remover colunas adicionadas
    op.drop_column('class_sessions', 'canceled_desc')
    op.drop_column('class_sessions', 'canceled')
    op.drop_column('class_sessions', 'confirmed_at')
    op.drop_column('class_sessions', 'date')
    
    # Remover teacher_id da tabela class_groups
    op.drop_constraint(None, 'class_groups', type_='foreignkey')
    op.drop_column('class_groups', 'teacher_id')
    
    # ### end Alembic commands ###